name: generate-codex-index

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
          submodules: recursive

      - name: Generate documentation index
        run: |
          python scripts/generate_index.py

      - name: Extract codex gitlog
        run: |
          git log -n 20 --grep '#codex:' --pretty=format:'%H %s' > .codex_gitlog.json

      - name: Commit index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add instructions/_INDEX.md instructions/vendors .codex_gitlog.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update codex index"
            git push
          fi
