name: generate-codex-index

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
          submodules: recursive

      - name: Generate codex.json
        run: |
          python - <<'PY'
          import os, json

          sources = []

          scenarios = os.path.join('instructions', '_scenarios')
          if os.path.isdir(scenarios):
              for root, _, files in os.walk(scenarios):
                  for name in sorted(files):
                      sources.append(os.path.join(root, name))

          if os.path.isdir('app'):
              for root, dirs, _ in os.walk('app'):
                  dirs.sort()
                  sources.append(root.rstrip('/') + '/')

          if os.path.isdir('vendor'):
              for entry in sorted(os.listdir('vendor')):
                  vend_path = os.path.join('vendor', entry)
                  if os.path.isdir(vend_path):
                      for root, dirs, _ in os.walk(vend_path):
                          dirs.sort()
                          sources.append(root.rstrip('/') + '/')

          sources.extend(['instructions/', 'sample_data/'])

          with open('codex.json', 'w') as f:
              json.dump({'sources': sources}, f)
          PY

      - name: Extract codex gitlog
        run: |
          git log -n 20 --grep '#codex:' --pretty=format:'%H %s' > .codex_gitlog.json

      - name: Commit index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add codex.json .codex_gitlog.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update codex index"
            git push
          fi
