name: generate-codex-index

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
          submodules: recursive

      - name: Generate codex.json
        run: |
          python - <<'PY'
import os, json
paths = []
for base in ['instructions', 'vendor', 'app']:
    if os.path.isdir(base):
        for root, dirs, files in os.walk(base):
            for name in dirs+files:
                p = os.path.join(root, name)
                paths.append(p)
with open('codex.json', 'w') as f:
    json.dump({'paths': paths}, f)
PY

      - name: Extract codex gitlog
        run: |
          git log -n 20 --grep '#codex:' --pretty=format:'%H %s' > .codex_gitlog.json

      - name: Commit index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add codex.json .codex_gitlog.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update codex index"
            git push
          fi
