name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest -v
      - name: Run clone_templates
        run: bash ./scripts/clone_templates.sh
      - name: Shellcheck
        run: |
          shellcheck scripts/*.sh || true
