name: validate-commits

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Validate commit messages
        run: |
          pattern='^(feat|fix|refactor|docs|chore|test)\([^)]+\): .+ #codex:.+'
          git log origin/${{ github.base_ref }}..HEAD --pretty=%s | while read line; do
            if ! [[ "$line" =~ $pattern ]]; then
              echo "::error ::Invalid commit message: $line"
              exit 1
            fi
          done
